"""Auto migration

Revision ID: 2fd786bd48cf
Revises: 
Create Date: 2025-10-06 11:55:35.825925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fd786bd48cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_session_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('story_text', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_panels', sa.Integer(), nullable=True),
    sa.Column('current_panel', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_tasks_created_at'), 'manga_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_manga_tasks_status'), 'manga_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_manga_tasks_user_session_id'), 'manga_tasks', ['user_session_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_activity', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_last_activity'), 'user_sessions', ['last_activity'], unique=False)
    op.create_table('manga_panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['manga_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_panels_task_id'), 'manga_panels', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_panels_task_id'), table_name='manga_panels')
    op.drop_table('manga_panels')
    op.drop_index(op.f('ix_user_sessions_last_activity'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_manga_tasks_user_session_id'), table_name='manga_tasks')
    op.drop_index(op.f('ix_manga_tasks_status'), table_name='manga_tasks')
    op.drop_index(op.f('ix_manga_tasks_created_at'), table_name='manga_tasks')
    op.drop_table('manga_tasks')
    # ### end Alembic commands ###