"""add_style_preference_fields_to_manga_task

Revision ID: 9cf552681961
Revises: c5f7131fd383
Create Date: 2025-10-06 21:12:29.646491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf552681961'
down_revision = 'c5f7131fd383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manga_panels', 'is_regenerated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('manga_tasks', sa.Column('art_style', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('mood', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('color_palette', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('character_style', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('line_style', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('composition', sa.String(length=100), nullable=True))
    op.add_column('manga_tasks', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga_tasks', 'additional_notes')
    op.drop_column('manga_tasks', 'composition')
    op.drop_column('manga_tasks', 'line_style')
    op.drop_column('manga_tasks', 'character_style')
    op.drop_column('manga_tasks', 'color_palette')
    op.drop_column('manga_tasks', 'mood')
    op.drop_column('manga_tasks', 'art_style')
    op.alter_column('manga_panels', 'is_regenerated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###