"""Add panel regeneration fields to MangaPanel

Revision ID: c5f7131fd383
Revises: 2fd786bd48cf
Create Date: 2025-10-06 18:06:35.869819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5f7131fd383'
down_revision = '2fd786bd48cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_panels', sa.Column('original_panel_id', sa.UUID(), nullable=True))
    op.add_column('manga_panels', sa.Column('regeneration_request', sa.Text(), nullable=True))
    op.add_column('manga_panels', sa.Column('is_regenerated', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_manga_panels_original_panel_id'), 'manga_panels', ['original_panel_id'], unique=False)
    op.create_index(op.f('ix_manga_panels_is_regenerated'), 'manga_panels', ['is_regenerated'], unique=False)
    op.create_foreign_key(None, 'manga_panels', 'manga_panels', ['original_panel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manga_panels', type_='foreignkey')
    op.drop_index(op.f('ix_manga_panels_is_regenerated'), table_name='manga_panels')
    op.drop_index(op.f('ix_manga_panels_original_panel_id'), table_name='manga_panels')
    op.drop_column('manga_panels', 'is_regenerated')
    op.drop_column('manga_panels', 'regeneration_request')
    op.drop_column('manga_panels', 'original_panel_id')
    # ### end Alembic commands ###